### ISSUE TITLE
2FA with steamcmd

### ISSUE THREAD

**Issue by TylerBre** [germanrcuriel/assetto-corsa-server#1]
How do you get this to work with steam 2FA? I may be missing something but the script does not inherit IO from steamcmd, it will just continue execution regardless of what steamcmd prompts?

**Comment by TylerBre** [comment]
FWIW, I've gotten this working with nodejs, but docker is obviously a different beast:

https://github.com/TylerBre/acserver_manager/blob/master/bin/acserver_update.js#L47

the key part being ```{ stdio: 'inherit' }``` for child_process. execSync

**Comment by TylerBre** [comment]
It does help. 

Are you able to get all the dlc with a dummy steam account that doesn't own the game/dlc?

**Comment by germanrcuriel** [comment]
When you install a DLC, as far as I know, files from that DLC don't get copied to the server folder. For this, you need to manually copy the files needed from your game installation to the shared folder or use the Windows server executable to upload the files to a remote server. That's how I do it. It works the very same way as installing a MOD.

<img width="682" alt="screen shot 2018-05-30 at 20 04 57" src="https://user-images.githubusercontent.com/706729/40738868-ecc51258-6444-11e8-8e69-d51ef32af98b.png">
For tracks you only need to copy from your installed game path the `ini` files you can see there (and more if the track have more layouts but basically `models.ini`, `surfaces.ini` and `drs_zones.ini` using the folder structure you see for `imola`.

For multiple layout tracks:
<img width="680" alt="screen shot 2018-05-30 at 20 08 35" src="https://user-images.githubusercontent.com/706729/40738976-4509c094-6445-11e8-876a-6a83ffcf46c1.png">

And for cars, more or less the same thing but you only need to copy the `data.acd` file.
<img width="681" alt="screen shot 2018-05-30 at 20 09 43" src="https://user-images.githubusercontent.com/706729/40739033-6a687114-6445-11e8-9609-5a5814ce7ba1.png">

**Comment by TylerBre** [comment]
so you would need to manually install the dlc data files. that solution kind of sucks, but I get it.

**Comment by germanrcuriel** [comment]
The only way it can get "automated" is if you have a FTP with the shared folder that the docker image needs for the game server files and using the game server executable that has a functionality to update the server files.

You can see a detailed guide of the server windows GUI in this reddit  https://www.reddit.com/r/assettocorsa/comments/2la21d/assetto_corsa_server_setup_guide/

**Comment by germanrcuriel** [comment]
There is a video that covers how to use and update the server by using the windows GUI. Hope it helps https://www.youtube.com/watch?annotation_id=annotation_553406171&feature=iv&src_vid=RiHYypBkQok&v=N_e0UAtX8Hk

**Comment by germanrcuriel** [comment]
So, long story short there are two "common" ways to deal with the dedicated server updates:

1. Upload/copy the content manually
2. Make an FTP server that serves the docker shared folder and use your `Steam folder\steamapps\common\assettocorsa\server\acServerManager.exe` by setting up the FTP connection and syncing the content from that app.

Sorry for the spam.

**Comment by germanrcuriel** [comment]
It depends on how you want to manage it. I usually don't manage the server from windows so I have a script that copies the files from mods when i put them in a watched "downloads" folder that I have in the docker shared folder. This way you can manage it the way you want 😉

**Comment by TylerBre** [comment]
Closing, but I forked this because I want to roll in https://github.com/Pringlez/ACServerManager into this docker image.

The end goal is to host many of these docker images on a digital ocean box with a simple 1 click install.

I'll keep you updated :)

**Comment by germanrcuriel** [comment]
Wow cool! I will look forward to that :) 

Thanks again!

**Comment by TylerBre** [comment]
No problem and thanks for your hard work on this!

**Comment by TylerBre** [comment]
@germanrcuriel 

http://www.n-e-y-s.de/downloads/stracker/stable/stracker-V3.4.1.zip

is 404'ing :tired_face:  can't build locally, and neither will you be able to. Is there a place where these binaries are hosted? not on github from what I can tell.

**Comment by germanrcuriel** [comment]
They turned down the site because the owner says this:

>> Server admins decide to run this software on their own judgement. The software creates a database where personal information of players is stored and processed, including their Steam GUID, nick name, chat history and game play statistics. This might require special efforts to ensure that the offered service obeys to national and international laws and policies.
Please understand that this software is a private hobby project and so the software might not fit to current or future legal regulations, including, but not limited to, the EU GDPR (https://www.eugdpr.org/). It might even be illegal to run this software on a public server. You are running this software on your own risk.
